//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueaderoMatt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATOS_VEHICULO()
        {
            this.REGISTRO_INGRESO = new HashSet<REGISTRO_INGRESO>();
            this.REGISTRO_EMPLEADO_VEHICULO = new HashSet<REGISTRO_EMPLEADO_VEHICULO>();
        }
    
        public System.Guid ID_DATOS_VEHICULO { get; set; }
        public string CILINDAJE_MOTO { get; set; }
        public string TIEMPO_MOTO { get; set; }
        public string PLACA_MOTO_CARRO { get; set; }
        public string MODELO_CARRO { get; set; }
        public Nullable<int> NUMERO_PUERTAS_CARRO { get; set; }
        public string MARCA_BICI { get; set; }
        public string COLOR_BICI { get; set; }
        public string FOTO_VEHICULO { get; set; }
        public System.Guid ID_TIPO_VEHICULO { get; set; }
    
        public virtual TIPO_VEHICULO TIPO_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_INGRESO> REGISTRO_INGRESO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_EMPLEADO_VEHICULO> REGISTRO_EMPLEADO_VEHICULO { get; set; }
    }
}
