//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueaderoMatt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.REGISTRO_INGRESO = new HashSet<REGISTRO_INGRESO>();
            this.REGISTRO_INGRESO1 = new HashSet<REGISTRO_INGRESO>();
            this.REGISTRO_EMPLEADO_VEHICULO = new HashSet<REGISTRO_EMPLEADO_VEHICULO>();
        }
    
        public System.Guid ID_PERSONA { get; set; }
        public string IDENTIFICACION_PERSONA { get; set; }
        public System.Guid TIPO_IDENTIFICACION_PERSONA { get; set; }
        public string NOMBRE1_PERSONA { get; set; }
        public string NOMBRE2_PERSONA { get; set; }
        public string APELLIDO1_PERSONA { get; set; }
        public string APELLIDO2_PERSONA { get; set; }
        public System.Guid ID_CARGO { get; set; }
        public System.Guid ID_TIPO_PERSONA { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual TIPO_IDENTIFICACION TIPO_IDENTIFICACION { get; set; }
        public virtual TIPO_PERSONA TIPO_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_INGRESO> REGISTRO_INGRESO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_INGRESO> REGISTRO_INGRESO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_EMPLEADO_VEHICULO> REGISTRO_EMPLEADO_VEHICULO { get; set; }
    }
}
