//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueaderoMatt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_EMPLEADO_VEHICULO
    {
        public System.Guid ID_REGISTRO_EMPLEADO_VEHICULO { get; set; }
        public System.Guid ID_PERSONA { get; set; }
        public System.Guid ID_DATOS_VEHICULO { get; set; }
        public int NRO_CELDA_ASIGNADA { get; set; }
    
        public virtual DATOS_VEHICULO DATOS_VEHICULO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
