//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueaderoMatt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_IDENTIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_IDENTIFICACION()
        {
            this.PERSONA = new HashSet<PERSONA>();
        }
    
        public System.Guid ID_TIPO_IDENTIFICACION { get; set; }
        public string TIPO_IDENTIFICACION1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONA> PERSONA { get; set; }
    }
}
