//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueaderoMatt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_VEHICULO()
        {
            this.DATOS_VEHICULO = new HashSet<DATOS_VEHICULO>();
        }
    
        public System.Guid ID_TIPO_VEHICULO { get; set; }
        public string TIPO_VEHICULO1 { get; set; }
        public string APLICA_ALIVIO { get; set; }
        public decimal VALOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATOS_VEHICULO> DATOS_VEHICULO { get; set; }
    }
}
